CREATE TABLE IF NOT EXISTS WORDS (
    id SERIAL NOT NULL,
    word VARCHAR(255) NOT NULL,
    description VARCHAR(2048) NOT NULL,
    last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    priority INT,
    PRIMARY KEY (id)
);