services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '8080:8080'
    environment:
      - AWS_REGION=ap-southeast-1
      - DYNAMODB_ENDPOINT=https://dynamodb.ap-southeast-1.amazonaws.com
